= Qu'est ce que l'APM ?
:hp-tags: Définition

== APM ou Application performance management

L’Application Performance Management (APM) permet de superviser les applications en environnements de production et de recettes qu’elles soient hébergées en interne ou en externe afin de diagnostiquer en temps réel les incidents ou ralentissements dans vos applications.

Votre application n’est plus une boite noire, surveillez son comportement comme vous le faites pour votre infrastructure et votre réseau.

Les temps de réponse de votre application se dégradent en production, et pourtant aucune alerte pertinente n'est remontée par les systèmes de supervision des infrastructures  ou des réseaux. 

Les méthodes classiques de tests de performances et les interventions ponctuelles d'experts pour des audits de performance ne permettent pas de diagnostiquer les problèmes en temps réel et de remettre les applications en service dans le respect des SLA. 

Il est possible de fournir à l'aide d’un outil de supervision et de diagnostic de performance applicative de bout en bout des informations précises et ciblées aux différentes équipes impliquées par les problèmes de performance comme le support de production, les développeurs, les architectes logiciels ou encore les administrateurs des différents composants techniques. 

Cette pratique permet aux équipes informatiques de comprendre le comportement interne de leurs applications en production, d’être alertées en temps réel, d’assurer une meilleure qualité de service pour les utilisateurs afin d’augmenter leur satisfaction et dans la plupart des situations d’apporter plus de revenus à la société.